class MainLocators:
    button_order = "//button[contains(@class,'Button_Button__ra12g')]"  # локатор для кнопки "Заказать" вверху стр
    button_order_mid = "//button[contains(@class, 'Button_Button__ra12g Button_Middle__1CSJM')]"  # локатор для кнопки "Заказать" в середине стр
    button_cookie_accept = "//button[contains(text(),'да все привыкли')]"
    name_input = "//input[@placeholder = '* Имя']"
    surname_input = "//input[@placeholder = '* Фамилия']"
    where_input = "//input[@placeholder = '* Адрес: куда привезти заказ']"
    metro = "//input[@placeholder = '* Станция метро']"
    phone = "//input[@placeholder = '* Телефон: на него позвонит курьер']"
    select_by_value = "//div[contains(@class,'select-search__select')]/ul/li"
    click_next = "//button[contains(text(),'Далее')]"
    date_input = "//input[@placeholder = '* Когда привезти самокат']"
    choose_date = "//div[contains(@class,'react-datepicker__day react-datepicker__day--006 react-datepicker__day--selected react-datepicker__day--today')]"
    period_click = "//div[contains(@class,'Dropdown-placeholder')]"
    choose_period = "//*[contains(@class,'Dropdown-option') and contains(text(),'сутки')]"
    input_color = '//input[@id="black"]'
    input_comment = "//input[@placeholder = 'Комментарий для курьера']"
    click_order = "//*[contains(@class,'Button_Button__ra12g Button_Middle__1CSJM') and contains(text(),'Заказать')]"
    order_yes_button = "//button[contains(text(),'Да')]"
    button_check_order = "//button[contains(text(),'Посмотреть статус')]"

    QUESTION1 = "(By.ID, *accordion__heading-0*)"
    ANS_Q1 = "(By.ID, *accordion__panel-0*)"
    QUESTION2 = "(By.ID, *accoridon__heading-1*)"
    ANS_Q2 = "(By.ID, *accordion__panel-1*)"
    QUESTION3 = "(By.ID, *accordion__heading-2*)"
    ANS_Q3 = "(By.ID, *accordion__panel-2*)"
    QUESTION4 = "(By.ID, *accordion__heading-3*)"
    ANS_Q4 = "(By.ID, *accordion__panel-3*)"
    QUESTION5 = "(By.ID, *accordion__heading-4*)"
    ANS_Q5 = "(By.ID, *accordion__panel-4*)"
    QUESTION6 = "(By.ID, *accordion__heading-5*)"
    ANS_Q6 = "(By.ID, *accordion__panel-5*)"
    QUESTION7 = "(By.ID, *accordion__heading-6*)"
    ANS_Q7 = "(By.ID, *accordion__panel-6*)"
    QUESTION8 = "(By.ID, *accordion__heading-7*)"
    ANS_Q8 = "(By.ID, *accordion__panel-7*)"
    Question = "(By.ID, *accordion__heading-{number}*)"
    Answer = "(By.ID, *accordion__panel-{number}*)"
    yes_all = "//button[contains(text(),'да все привыкли')]"
    question = "(By.ID, f'accordion__heading-{i}')"
    answer = "(By.ID, f'accordion__panel-{i}')"

    logo_samokat_click = "//a[contains(@class,'Header_LogoScooter__3lsAR')]"
    logo_ya_click = "//a[contains(@class,'Header_LogoYandex__3TSOI')]"
